package(default_visibility = ["//visibility:public"])

## example template for defining a library package build rule
##
# cc_library(
#     name = "<NAME_OF_LIBRARY_PACKAGE>",
#     hdrs = ["<HEADER_FILE>"],
#     srcs = ["<SOURCE_FILE>"],
#     deps = [
#         "//ir:ir",
#         "//util:standard_includes",
#         ":<ANY_OTHER_DEPENDENCIES>",
#     ],
# )

## example template for defining a test suite build rule for a library package
##
# cc_test(
#     name = "<NAME_OF_LIBRARY_PACKAGE>_test",
#     srcs = ["<NAME>_test.cc"],
#     deps = [":<NAME_OF_LIBRARY_PACKAGE>"],
# )
